"""Expose immutable deterministic search contracts and the catalog-backed service."""

# Package Library
from kgfegmcp.search.models import (
    CodeMatchEvidence,
    CodeParentDerivationEvidence,
    CodeParentDerivationStatus,
    CodeScopeEvidence,
    ExactCodeSearchQuery,
    ExactPackageSearchScope,
    ExactPhraseTextMatch,
    FederatedPackageSearchScope,
    PackageSearchIndexMetadata,
    PackageSearchScope,
    PrefixCodeSearchQuery,
    SearchCursor,
    SearchFacetEvidence,
    SearchField,
    SearchFilters,
    SearchHit,
    SearchIndexMetadata,
    SearchMatchedField,
    SearchMode,
    SearchPage,
    SearchQuery,
    SearchScore,
    SearchScoreAlgorithm,
    SearchSelectionMode,
    SearchWarning,
    SearchWarningCode,
    TextMatch,
    TextMatchMode,
    TextOperator,
    TextSearchQuery,
    TokenTextMatch,
)
from kgfegmcp.search.service import SearchService

__all__ = [
    "CodeMatchEvidence",
    "CodeParentDerivationEvidence",
    "CodeParentDerivationStatus",
    "CodeScopeEvidence",
    "ExactCodeSearchQuery",
    "ExactPackageSearchScope",
    "ExactPhraseTextMatch",
    "FederatedPackageSearchScope",
    "PackageSearchIndexMetadata",
    "PackageSearchScope",
    "PrefixCodeSearchQuery",
    "SearchCursor",
    "SearchFacetEvidence",
    "SearchField",
    "SearchFilters",
    "SearchHit",
    "SearchIndexMetadata",
    "SearchMatchedField",
    "SearchMode",
    "SearchPage",
    "SearchQuery",
    "SearchScore",
    "SearchScoreAlgorithm",
    "SearchSelectionMode",
    "SearchService",
    "SearchWarning",
    "SearchWarningCode",
    "TextMatch",
    "TextMatchMode",
    "TextOperator",
    "TextSearchQuery",
    "TokenTextMatch",
]
