"""Validate complete checksum-verified LP evidence before retaining small projections.

These checks consume loader-owned bytes, never a resource read or a private producer
path. Rich documents exist only during acceptance; the returned aggregate contains
bounded scalar/tuple projections and cannot serve as a second mutable graph store.
"""

# Standard Library
import hashlib
import json

from collections import Counter
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Final, cast

# Third Party Library
from pydantic import TypeAdapter, ValidationError

# Package Library
from kgfegmcp.domain.enums import GraphType
from kgfegmcp.errors import ManifestBuildError
from kgfegmcp.graph.models import GraphRelationship
from kgfegmcp.packages.checksums import calculate_bytes_sha256
from kgfegmcp.packages.lp_graph import LP_TYPES
from kgfegmcp.packages.lp_models import (
    Claim,
    CoverageProjection,
    CycleDiagnostics,
    FinalClaims,
    JudgmentProjection,
    LearningProgressionEvidence,
    Provenance,
    RawHash,
    Summary,
    Unresolved,
    ValidationReport,
)
from kgfegmcp.packages.models import LoadedGraphPackage, PackageValidationFinding
from kgfegmcp.packages.normalization_models import (
    DetailedLearningProgression,
    LearningProgressionProvenanceIndex,
    NormalizationReceipt,
)
from kgfegmcp.packages.normalization_sources import COPIED_BASENAMES, read_json_object

_ATTRIBUTION_TEMPLATE: Final[str] = (
    "Learning progression relationship generated by IDinsight using an LLM "
    "producer/checker workflow. Source framework attribution: "
    "{source_attribution_statement}. This inferred relationship was not stated "
    "or endorsed by the source publisher."
)
_DECISIONS: Final[tuple[str, ...]] = (
    "buildsTowards",
    "relatesTo",
    "no_relation",
    "needs_review",
)
_PROPERTY_ALIASES: Final[dict[str, str]] = {
    "attribution_statement": "attributionStatement",
    "author": "author",
    "date_created": "dateCreated",
    "date_modified": "dateModified",
    "description": "description",
    "identifier": "identifier",
    "license": "license",
    "provider": "provider",
    "relationship_type": "relationshipType",
    "source_entity": "sourceEntity",
    "source_entity_key": "sourceEntityKey",
    "source_entity_value": "sourceEntityValue",
    "target_entity": "targetEntity",
    "target_entity_key": "targetEntityKey",
    "target_entity_value": "targetEntityValue",
}
_SCOPE_NOTICE: Final[str] = (
    "Validation covers structural and process integrity only; it does not "
    "establish pedagogical correctness."
)


class _EvidenceError(ValueError):
    """Carry a safe finding code without exposing a rich evidence value."""

    def __init__(self, *, code: str, record_id: str | None = None) -> None:
        """Initialize a structured acceptance failure.

        Parameters
        ----------
        code
            Public stable error classification.
        record_id
            Offending exported relationship, when applicable.

        Examples
        --------
        >>> str(_EvidenceError(code="lp_evidence_shape"))
        'lp_evidence_shape'
        """

        super().__init__(code)
        self.code = code
        self.record_id = record_id


@dataclass(frozen=True, slots=True)
class _Evidence:
    """Hold ephemeral parsed evidence solely for one acceptance pass."""

    contents: Mapping[str, bytes]
    final: FinalClaims
    final_raw: dict[str, object]
    package: LoadedGraphPackage
    provenance: dict[str, object]
    receipt: NormalizationReceipt
    report: ValidationReport
    split: dict[str, DetailedLearningProgression]
    summary: Summary
    unresolved: Unresolved


def _canonical_line(value: object) -> bytes:
    """Encode a deterministic normalized delivery line independently of preparation.

    Parameters
    ----------
    value
        Public wire record.

    Returns
    -------
    bytes
        UTF-8 record with one newline.

    Examples
    --------
    >>> _canonical_line({})
    b'{}\\n'
    """

    return (
        json.dumps(
            allow_nan=False,
            ensure_ascii=False,
            obj=value,
            separators=(",", ":"),
            sort_keys=True,
        )
        + "\n"
    ).encode("utf-8")


def _claim_endpoints(claim: Claim) -> tuple[str | None, str | None]:
    """Derive published endpoints from the stored judgment's explicit direction.

    Parameters
    ----------
    claim
        Validated final claim.

    Returns
    -------
    tuple[str | None, str | None]
        Directed builds endpoints, canonical relates endpoints, or no publication.

    Examples
    --------
    >>> _claim_endpoints(no_relation_claim)
    (None, None)
    """

    judgment = claim.judgment
    endpoints = (str(judgment.first_sfi_uuid), str(judgment.second_sfi_uuid))

    if judgment.decision == "buildsTowards":
        _require(code="lp_judgment_direction", condition=judgment.direction is not None)
        return endpoints if judgment.direction == "first_to_second" else endpoints[::-1]

    _require(code="lp_judgment_direction", condition=judgment.direction is None)

    if judgment.decision == "relatesTo":
        first, second = sorted(endpoints)
        return first, second

    return None, None


def _coverage(evidence: _Evidence) -> CoverageProjection:
    """Project source coverage with optional unknown selection denominators.

    Parameters
    ----------
    evidence
        Accepted report and summary evidence.

    Returns
    -------
    CoverageProjection
        Immutable counts, limits and bounded warnings.

    Examples
    --------
    >>> _coverage(evidence).semantic_scope_notice == _SCOPE_NOTICE
    True
    """

    eligibility = evidence.summary.eligibility
    warnings = evidence.report.warnings
    return CoverageProjection(
        eligible_sfis_per_relationship=(
            tuple(sorted(eligibility.eligible_sfis_per_relationship.items()))
            if eligibility
            else None
        ),
        exclusion_reason_counts=(
            tuple(
                sorted(
                    (label, reason, count)
                    for label, reasons in eligibility.exclusion_reason_counts_per_relationship.items()
                    for reason, count in reasons.items()
                )
            )
            if eligibility
            else None
        ),
        needs_review_claims=evidence.report.object_counts["needs_review_claims"],
        no_relation_claims=evidence.report.object_counts["no_relation_claims"],
        semantic_scope_notice=evidence.report.semantic_scope_notice,
        total_sfis_considered=(
            eligibility.total_sfis_considered if eligibility else None
        ),
        total_sfis_eligible=eligibility.total_sfis_eligible if eligibility else None,
        total_sfis_excluded=eligibility.total_sfis_excluded if eligibility else None,
        unresolved_participation=(
            eligibility.unresolved_participation if eligibility else None
        ),
        unresolved_sfis_counts=(
            tuple(
                (name, getattr(eligibility, name))
                for name in (
                    "unresolved_sfis_considered",
                    "unresolved_sfis_eligible",
                    "unresolved_sfis_excluded",
                    "unresolved_sfis_policy_excluded",
                )
            )
            if eligibility
            else None
        ),
        unresolved_warning_pairs=evidence.report.object_counts[
            "unresolved_warning_pairs"
        ],
        validation_warning_count=len(warnings),
        validation_warning_excerpts=tuple(warning[:512] for warning in warnings[:5]),
        validation_warnings_excerpted=any(
            len(warning) > 512 for warning in warnings[:5]
        ),
        validation_warnings_omitted=len(warnings) > 5,
    )


def _expected_wire(
    *, edge: DetailedLearningProgression, standards: Mapping[str, str]
) -> dict[str, object]:
    """Reconstruct slim delivery properties from the unchanged detailed edge.

    Parameters
    ----------
    edge
        Strict retained detailed LP record.
    standards
        Exact original CASE to outer-ID mapping.

    Returns
    -------
    dict[str, object]
        Complete expected delivery record, without rich metadata.

    Examples
    --------
    >>> _expected_wire(edge=edge, standards=standards)["label"] == edge.relationship_type
    True
    """

    original = edge.model_dump(mode="json")
    properties = {
        alias: original[name]
        for name, alias in _PROPERTY_ALIASES.items()
        if original[name] is not None
    }
    properties["sourceEntityKey"] = properties["targetEntityKey"] = "caseIdentifierUUID"
    _require(
        code="lp_detailed_endpoint_unresolved",
        condition=(
            edge.source_entity_value in standards
            and edge.target_entity_value in standards
        ),
        record_id=str(edge.identifier),
    )
    return {
        "identifier": str(edge.identifier),
        "label": edge.relationship_type,
        "properties": properties,
        "source_identifier": standards[edge.source_entity_value],
        "source_labels": ["StandardsFrameworkItem"],
        "target_identifier": standards[edge.target_entity_value],
        "target_labels": ["StandardsFrameworkItem"],
        "type": "relationship",
    }


def _load_evidence(
    *, contents: Mapping[str, bytes], package: LoadedGraphPackage
) -> _Evidence:
    """Parse complete retained documents from checksum-verified loader bytes.

    Parameters
    ----------
    contents
        Captured original bytes, including all LP partitions.
    package
        Decoded package being accepted.

    Returns
    -------
    _Evidence
        Ephemeral typed source evidence and exact original maps.

    Examples
    --------
    >>> _load_evidence(contents=verified_bytes, package=package).report.passed
    True
    """

    final = read_json_object(
        data=contents["learningProgressionFinalClaims"], label="LP final claims"
    )
    normalization = read_json_object(
        data=contents["learningProgressionNormalization"], label="LP normalization"
    )
    _require(
        code="lp_normalization_format",
        condition=normalization.get("formatVersion") == "1.0",
    )
    split: dict[str, DetailedLearningProgression] = {}

    for name, label in (
        ("learningProgressionBuildsTowards", "buildsTowards"),
        ("learningProgressionRelatesTo", "relatesTo"),
    ):
        for line in contents[name].splitlines():
            if not line.strip():
                continue

            edge = DetailedLearningProgression.model_validate(
                read_json_object(data=line, label=name)
            )
            _require(
                code="lp_detailed_identity_conflict",
                condition=edge.relationship_type == label
                and str(edge.identifier) not in split,
                record_id=str(edge.identifier),
            )
            split[str(edge.identifier)] = edge

    return _Evidence(
        contents=contents,
        final=FinalClaims.model_validate(final),
        final_raw=final,
        package=package,
        provenance=read_json_object(
            data=contents["learningProgressionProvenance"], label="LP provenance"
        ),
        receipt=NormalizationReceipt.model_validate(normalization),
        report=ValidationReport.model_validate(
            read_json_object(
                data=contents["learningProgressionValidation"], label="LP validation"
            )
        ),
        split=split,
        summary=Summary.model_validate(
            read_json_object(
                data=contents["learningProgressionSummary"], label="LP summary"
            )
        ),
        unresolved=Unresolved.model_validate(
            read_json_object(
                data=contents["learningProgressionUnresolved"], label="LP unresolved"
            )
        ),
    )


def _projection(*, identifier: str, provenance: Provenance) -> JudgmentProjection:
    """Retain the stored final model judgment with bounded excerpts and flags.

    Parameters
    ----------
    identifier
        Exact stored relationship identifier.
    provenance
        Complete validated per-edge evidence.

    Returns
    -------
    JudgmentProjection
        Small immutable query metadata.

    Examples
    --------
    >>> len(_projection(identifier=identifier, provenance=provenance).rationale_excerpt) <= 512
    True
    """

    judgment = provenance.claim.judgment
    return JudgmentProjection.model_validate(
        {
            "confidence": judgment.confidence,
            "rationale_excerpt": judgment.rationale[:512],
            "rationale_excerpted": len(judgment.rationale) > 512,
            "relationship_id": identifier,
            "warning_count": len(judgment.warnings),
            "warning_excerpts": tuple(
                warning[:512] for warning in judgment.warnings[:5]
            ),
            "warnings_excerpted": any(
                len(warning) > 512 for warning in judgment.warnings[:5]
            ),
            "warnings_omitted": len(judgment.warnings) > 5,
        }
    )


def _require(*, code: str, condition: bool, record_id: str | None = None) -> None:
    """Reject a failed evidence invariant with a safe structured finding.

    Parameters
    ----------
    code
        Public error category.
    condition
        Independently evaluated acceptance invariant.
    record_id
        Exact offending relationship when known.

    Examples
    --------
    >>> _require(code="lp_evidence_shape", condition=True)
    """

    if not condition:
        raise _EvidenceError(code=code, record_id=record_id)


def _validate_claim(claim: Claim) -> None:
    """Require candidate, final judgment, trace and exported selectors to agree.

    Parameters
    ----------
    claim
        One final publishing or nonpublishing decision.

    Examples
    --------
    >>> _validate_claim(valid_claim)
    """

    candidate = claim.candidate
    judgment = claim.judgment
    _require(
        code="lp_claim_identity_mismatch",
        condition=(
            candidate.pair_id == judgment.pair_id
            and candidate.first_sfi_uuid == judgment.first_sfi_uuid
            and candidate.second_sfi_uuid == judgment.second_sfi_uuid
            and candidate.first_sfi_uuid != candidate.second_sfi_uuid
            and {"decision": judgment.decision, "direction": judgment.direction}
            in candidate.admissible_decisions
        ),
    )
    _require(
        code="lp_claim_endpoint_mismatch",
        condition=(
            (claim.source_sfi_uuid, claim.target_sfi_uuid) == _claim_endpoints(claim)
        ),
    )
    producer = claim.provenance.producer_judgment
    _require(
        code="lp_trace_identity_mismatch",
        condition=(
            producer.pair_id == judgment.pair_id
            and producer.first_sfi_uuid == judgment.first_sfi_uuid
            and producer.second_sfi_uuid == judgment.second_sfi_uuid
        ),
    )


def _validate_final_claims(evidence: _Evidence) -> dict[str, object]:
    """Validate all final decisions and match excluded review evidence exactly.

    Parameters
    ----------
    evidence
        Complete typed and raw final/unresolved evidence.

    Returns
    -------
    dict[str, object]
        Exact original publishing claim values by candidate pair ID.

    Examples
    --------
    >>> len(_validate_final_claims(evidence)) == len(evidence.split)
    True
    """

    raw_claims = evidence.final_raw["claims"]
    _require(code="lp_final_claims_shape", condition=isinstance(raw_claims, list))
    accepted: dict[str, object] = {}
    pairs: set[tuple[str, ...]] = set()
    pair_ids: set[str] = set()
    review: list[Claim] = []
    review_raw: list[dict[str, object]] = []

    for claim, raw in zip(
        evidence.final.claims, cast(list[dict[str, object]], raw_claims), strict=True
    ):
        _validate_claim(claim)
        pair = tuple(
            sorted(
                (
                    str(claim.candidate.first_sfi_uuid),
                    str(claim.candidate.second_sfi_uuid),
                )
            )
        )
        _require(
            code="lp_final_pair_conflict",
            condition=(pair not in pairs and claim.candidate.pair_id not in pair_ids),
        )
        pairs.add(pair)
        pair_ids.add(claim.candidate.pair_id)

        if claim.judgment.decision in LP_TYPES:
            accepted[claim.candidate.pair_id] = raw
        elif claim.judgment.decision == "needs_review":
            review.append(claim)
            review_raw.append(raw)

    _require(
        code="lp_unresolved_mismatch",
        condition=(
            evidence.unresolved.claims == tuple(review)
            and read_json_object(
                data=evidence.contents["learningProgressionUnresolved"],
                label="LP unresolved",
            )["claims"]
            == review_raw
            and evidence.unresolved.total_needs_review == len(review)
            and evidence.unresolved.final_claims_content_hash
            == evidence.final.content_hash
        ),
    )
    counts = Counter(claim.judgment.decision for claim in evidence.final.claims)
    expected = {decision: counts[decision] for decision in _DECISIONS}
    _require(
        code="lp_final_counts_mismatch",
        condition=(
            evidence.final.decision_counts
            == evidence.summary.decision_counts
            == expected
            and evidence.final.total_claims == len(evidence.final.claims)
            and len(accepted) == len(evidence.split)
        ),
    )
    return accepted


def _validate_index(evidence: _Evidence) -> None:
    """Verify all 64 exact declarations, hashes, buckets and original entry values.

    Parameters
    ----------
    evidence
        Captured partitions and original provenance.

    Examples
    --------
    >>> _validate_index(valid_evidence)
    """

    raw = read_json_object(
        data=evidence.contents["learningProgressionProvenanceIndex"],
        label="LP provenance index",
    )
    _require(
        code="lp_partition_format",
        condition={
            "formatVersion",
            "originalProvenanceLogicalName",
            "originalProvenanceSha256",
            "partitionAlgorithm",
            "partitionCount",
            "partitions",
        }
        <= set(raw)
        and isinstance(raw.get("partitionCount"), int)
        and raw.get("partitionCount") == 64,
    )
    index = LearningProgressionProvenanceIndex.model_validate(raw)
    slots = {f"learningProgressionProvenanceShard{number:02d}" for number in range(64)}
    declared = evidence.package.manifest.artifacts.additional_artifacts
    _require(
        code="lp_partition_declarations",
        condition=(
            set(index.partitions) == slots
            and {
                str(name)
                for name in declared
                if str(name).startswith("learningProgressionProvenanceShard")
            }
            == slots
            and index.original_provenance_sha256
            == calculate_bytes_sha256(
                evidence.contents["learningProgressionProvenance"]
            )
        ),
    )
    union: dict[str, object] = {}

    for number in range(64):
        slot = f"learningProgressionProvenanceShard{number:02d}"
        partition = index.partitions[slot]
        reference = evidence.package.artifact(slot)
        _require(
            code="lp_partition_identity",
            condition=(
                reference is not None
                and str(partition.artifact_path)
                == f"additional/lp_relationship_provenance_shard_{number:02d}.json"
                and reference.package_path == partition.artifact_path
                and reference.sha256 == partition.sha256
            ),
        )
        bucket = read_json_object(data=evidence.contents[slot], label=slot)
        _require(
            code="lp_partition_contents",
            condition=(
                len(bucket) == partition.entry_count
                and not set(bucket).intersection(union)
                and all(
                    hashlib.sha256(identifier.encode("utf-8")).digest()[0] % 64
                    == number
                    for identifier in bucket
                )
            ),
        )
        union.update(bucket)

    _require(
        code="lp_partition_union",
        condition=(union == evidence.provenance and set(union) == set(evidence.split)),
    )


def _validate_normalization(evidence: _Evidence) -> None:
    """Independently bind preserved source bytes and normalized output to the receipt.

    Parameters
    ----------
    evidence
        Public receipt and loader's complete verified artifact references.

    Examples
    --------
    >>> _validate_normalization(valid_evidence)
    """

    receipt = evidence.receipt
    package = evidence.package
    TypeAdapter(RawHash).validate_python(receipt.document_key)
    _require(
        code="lp_normalization_identity",
        condition=(
            receipt.framework_id == package.manifest.framework_id
            and receipt.framework_case_uuid
            == package.framework_root.case_identifier_uuid
            and receipt.builds_towards_relationships
            == package.manifest.counts.builds_towards_relationships
            and receipt.relates_to_relationships
            == package.manifest.counts.relates_to_relationships
            and set(receipt.input_sha256) == COPIED_BASENAMES
        ),
    )
    outputs = {
        reference.package_path: reference.sha256
        for reference in package.artifacts
        if str(reference.logical_name) != "learningProgressionNormalization"
    }
    _require(
        code="lp_normalization_output_hashes",
        condition=receipt.output_sha256 == outputs,
    )

    for reference in package.artifacts:
        basename = PurePosixPath(str(reference.package_path)).name

        if basename in receipt.input_sha256:
            _require(
                code="lp_normalization_input_hashes",
                condition=(receipt.input_sha256[basename] == reference.sha256),
            )

    _validate_normalized_delivery(evidence)


def _validate_normalized_delivery(evidence: _Evidence) -> None:
    """Check the original AS/LC prefix and the entire appended LP wire suffix.

    Parameters
    ----------
    evidence
        Original split LP records and public source-byte receipt.

    Examples
    --------
    >>> _validate_normalized_delivery(valid_evidence)
    """

    receipt = evidence.receipt
    delivery = evidence.contents["relationships"]
    prefix = delivery[: receipt.as_lc_relationship_prefix_bytes]
    _require(
        code="lp_normalization_prefix",
        condition=(
            receipt.as_lc_relationship_prefix_bytes <= len(delivery)
            and calculate_bytes_sha256(prefix)
            == receipt.input_sha256["as_lc_relationships.jsonl"]
            and calculate_bytes_sha256(evidence.contents["nodes"])
            == receipt.input_sha256["as_lc_nodes.jsonl"]
            and receipt.newline_separator_added
            == bool(evidence.split and prefix and not prefix.endswith(b"\n"))
        ),
    )
    prefix_rows = tuple(
        read_json_object(data=line, label="AS/LC prefix")
        for line in prefix.splitlines()
        if line.strip()
    )
    _require(
        code="lp_normalization_prefix_types",
        condition=all(
            row.get("label") in {"hasChild", "supports"} for row in prefix_rows
        ),
    )
    standards = {
        str(node.case_identifier_uuid): str(node.node_id)
        for node in evidence.package.item_nodes
        if node.case_identifier_uuid is not None
    }
    suffix = b"\n" if receipt.newline_separator_added else b""

    suffix += b"".join(
        _canonical_line(_expected_wire(edge=edge, standards=standards))
        for edge in sorted(
            evidence.split.values(),
            key=lambda edge: (edge.relationship_type, edge.identifier),
        )
    )

    _require(
        code="lp_normalization_delivery_mismatch",
        condition=(delivery[receipt.as_lc_relationship_prefix_bytes :] == suffix),
    )


def _validate_provenance(
    *, accepted: Mapping[str, object], evidence: _Evidence
) -> tuple[JudgmentProjection, ...]:
    """Match each exported edge to complete source evidence and an exact final claim.

    Parameters
    ----------
    accepted
        Original publishing claims indexed by pair ID.
    evidence
        Loaded delivery, retained split edges and original provenance.

    Returns
    -------
    tuple[JudgmentProjection, ...]
        Bounded immutable validated judgments sorted by relationship ID.

    Examples
    --------
    >>> len(_validate_provenance(accepted=accepted, evidence=evidence)) == len(evidence.split)
    True
    """

    edges = {
        str(edge.relationship_id): edge
        for edge in evidence.package.relationships
        if edge.label in LP_TYPES
    }
    _require(
        code="lp_provenance_ids",
        condition=set(edges) == set(evidence.provenance) == set(evidence.split),
    )
    projections: list[JudgmentProjection] = []
    seen: set[str] = set()

    for identifier, raw in sorted(evidence.provenance.items()):
        _require(
            code="lp_provenance_shape",
            condition=isinstance(raw, dict),
            record_id=identifier,
        )
        raw = cast(dict[str, object], raw)
        provenance = Provenance.model_validate(raw)
        _validate_claim(provenance.claim)
        pair_id = provenance.claim.candidate.pair_id
        _require(
            code="lp_provenance_final_claim",
            condition=(
                raw.get("claim") == accepted.get(pair_id)
                and pair_id not in seen
                and evidence.split[identifier].metadata == raw
                and provenance.claim.judgment.decision == edges[identifier].label
                and provenance.claim.source_sfi_uuid
                == edges[identifier].source_entity_value
                and provenance.claim.target_sfi_uuid
                == edges[identifier].target_entity_value
                and provenance.final_claims_content_hash == evidence.final.content_hash
            ),
            record_id=identifier,
        )
        seen.add(pair_id)
        _validate_source_credit(
            edge=edges[identifier], evidence=evidence, provenance=provenance
        )
        _validate_request_identity(evidence=evidence, provenance=provenance)
        projections.append(_projection(identifier=identifier, provenance=provenance))

    _require(code="lp_nonpublishing_exclusion", condition=seen == set(accepted))
    return tuple(projections)


def _validate_report(evidence: _Evidence) -> None:
    """Check passed/errors/counts, cross-document references and original byte hashes.

    Parameters
    ----------
    evidence
        Server-counted LP edges and retained upstream reports.

    Examples
    --------
    >>> _validate_report(valid_evidence)
    """

    report = evidence.report
    summary = evidence.summary
    counts = Counter(edge.relationship_type for edge in evidence.split.values())
    decisions = Counter(claim.judgment.decision for claim in evidence.final.claims)
    expected = {
        "builds_towards_claims": decisions["buildsTowards"],
        "builds_towards_relationships": counts["buildsTowards"],
        "candidate_pairs": len(evidence.final.claims),
        "final_claims": len(evidence.final.claims),
        "identifier_collisions": 0,
        "needs_review_claims": decisions["needs_review"],
        "no_relation_claims": decisions["no_relation"],
        "relates_to_claims": decisions["relatesTo"],
        "relates_to_relationships": counts["relatesTo"],
        "relationship_provenance": len(evidence.provenance),
        "relationships": len(evidence.split),
        "requests": len(evidence.final.claims),
        "unresolved_failed_pairs": 0,
    }
    _require(
        code="lp_report_status",
        condition=(
            report.passed
            and not report.errors
            and report.semantic_scope_notice == _SCOPE_NOTICE
            and not report.pedagogical_correctness_established
            and not report.semantic_validation_performed
            and summary.validation_report_passed
        ),
    )
    _require(
        code="lp_report_counts",
        condition=all(
            report.object_counts.get(name) == summary.object_counts.get(name) == value
            for name, value in expected.items()
        ),
    )
    _require(
        code="lp_report_process_counts",
        condition=(
            "generation_failure_attempts" in report.object_counts
            and "unresolved_warning_pairs" in report.object_counts
            and all(
                summary.object_counts.get(name) == count
                for name, count in report.object_counts.items()
            )
            and summary.object_counts.get("accepted_claims") == len(evidence.split)
            and summary.object_counts.get("nonpublishing_claims")
            == decisions["no_relation"] + decisions["needs_review"]
            and summary.object_counts.get("resolved_failure_attempts")
            == report.object_counts["generation_failure_attempts"]
        ),
    )
    _require(
        code="lp_report_references",
        condition=(
            summary.validation_report_content_hash == report.content_hash
            and summary.relationships_final_claims_content_hash
            == evidence.final.content_hash
            and report.input_content_hashes.get("final_claims")
            == evidence.final.content_hash
            and report.input_content_hashes.get("checkpoint_receipt_bytes")
            == evidence.final.checkpoint_receipt_byte_hash
            and all(
                summary.input_content_hashes.get(name) == value
                for name, value in report.input_content_hashes.items()
            )
        ),
    )
    _validate_report_hashes(evidence)
    _validate_report_topology(evidence)
    _validate_request_set(evidence)


def _validate_report_hashes(evidence: _Evidence) -> None:
    """Distinguish retained original byte hashes from external producer references.

    Parameters
    ----------
    evidence
        Summary byte identities and manifest-verified artifact references.

    Examples
    --------
    >>> _validate_report_hashes(valid_evidence)
    """

    references = {
        PurePosixPath(str(reference.package_path)).name: reference
        for reference in evidence.package.artifacts
    }
    required = {
        "lp_relationship_provenance.json",
        "lp_relationships_builds_towards.jsonl",
        "lp_relationships_relates_to.jsonl",
        "lp_unresolved_items.json",
        "lp_validation_report.json",
    }
    _require(
        code="lp_summary_byte_hashes",
        condition=required <= set(evidence.summary.artifact_byte_hashes),
    )

    for basename, raw_hash in evidence.summary.artifact_byte_hashes.items():
        if basename in references:
            _require(
                code="lp_summary_byte_hashes",
                condition=("sha256:" + raw_hash == references[basename].sha256),
            )

    for basename, raw_hash in evidence.summary.input_artifact_byte_hashes.items():
        if basename in references:
            _require(
                code="lp_summary_input_byte_hashes",
                condition=("sha256:" + raw_hash == references[basename].sha256),
            )


def _validate_report_topology(evidence: _Evidence) -> None:
    """Compare producer cycle counts and selection limits to independent graph facts.

    Parameters
    ----------
    evidence
        Final/report topology diagnostics and optional eligibility evidence.

    Examples
    --------
    >>> _validate_report_topology(valid_evidence)
    """

    builds = tuple(
        edge
        for edge in evidence.split.values()
        if edge.relationship_type == "buildsTowards"
    )
    nodes = {
        value
        for edge in builds
        for value in (edge.source_entity_value, edge.target_entity_value)
    }
    expected = CycleDiagnostics(
        components=(),
        cyclic_component_count=0,
        cyclic_edge_count=0,
        cyclic_node_count=0,
        graph_edge_count=len(builds),
        graph_node_count=len(nodes),
    )
    _require(
        code="lp_report_cycle_diagnostics",
        condition=(
            evidence.report.cycle_diagnostics
            == evidence.final.cycle_diagnostics
            == expected
        ),
    )
    eligibility = evidence.summary.eligibility

    if eligibility is not None:
        _require(
            code="lp_eligibility_mismatch",
            condition=(
                eligibility.framework_uuid
                == evidence.package.framework_root.case_identifier_uuid
                and eligibility.total_sfis_considered
                == len(evidence.package.item_nodes)
                and eligibility.total_sfis_eligible + eligibility.total_sfis_excluded
                == eligibility.total_sfis_considered
                and eligibility.unresolved_sfis_eligible
                + eligibility.unresolved_sfis_excluded
                == eligibility.unresolved_sfis_considered
                and set(eligibility.eligible_sfis_per_relationship) == LP_TYPES
            ),
        )


def _validate_request_identity(*, evidence: _Evidence, provenance: Provenance) -> None:
    """Bind per-edge generation identities to the retained final request manifest.

    Parameters
    ----------
    evidence
        Final request/execution evidence and sanitized normalization identity.
    provenance
        One complete retained per-edge trace.

    Examples
    --------
    >>> _validate_request_identity(evidence=evidence, provenance=provenance)
    """

    manifest = evidence.final.request_manifest.model_dump(mode="json")
    names = (
        "candidate_pairs_content_hash",
        "candidate_summary_content_hash",
        "config_content_hash",
        "doc_key",
        "requests_content_hash",
        "upstream_content_hash",
    )
    _require(
        code="lp_request_identity_mismatch",
        condition=(
            all(manifest.get(name) == getattr(provenance, name) for name in names)
            and manifest.get("artifact_byte_hashes")
            == provenance.candidate_artifact_byte_hashes
            and provenance.doc_key == evidence.receipt.document_key
            and manifest.get("framework_uuid") == evidence.receipt.framework_case_uuid
            and provenance.claim.candidate.pair_id in manifest.get("pair_ids", [])
            and provenance.claim.provenance.request_id
            in manifest.get("request_ids", [])
            and evidence.final.execution_material.get("model_config")
            == provenance.model_configuration
            and evidence.final.execution_material.get("model_settings")
            == provenance.model_settings
        ),
    )


def _validate_request_set(evidence: _Evidence) -> None:
    """Verify complete request coverage even when no LP edges are published.

    Parameters
    ----------
    evidence
        Final request set, public framework identity and execution material.

    Examples
    --------
    >>> _validate_request_set(valid_evidence)
    """

    final = evidence.final
    manifest = final.request_manifest
    _require(
        code="lp_request_set_mismatch",
        condition=(
            manifest.doc_key == evidence.receipt.document_key
            and manifest.framework_uuid == evidence.receipt.framework_case_uuid
            and manifest.total_candidate_pairs
            == manifest.total_requests
            == len(final.claims)
            and len(manifest.pair_ids)
            == len(set(manifest.pair_ids))
            == len(final.claims)
            and len(manifest.request_ids)
            == len(set(manifest.request_ids))
            == len(final.claims)
            and set(manifest.pair_ids)
            == {claim.candidate.pair_id for claim in final.claims}
            and set(manifest.request_ids)
            == {claim.provenance.request_id for claim in final.claims}
            and final.execution_material.get("request_manifest")
            == manifest.model_dump(mode="json")
            and final.execution_material.get("config_content_hash")
            == evidence.report.input_content_hashes.get("effective_config")
        ),
    )
    eligibility = evidence.summary.eligibility

    if eligibility is not None:
        _require(
            code="lp_request_eligibility_mismatch",
            condition=(
                eligibility.config_content_hash == manifest.config_content_hash
                and eligibility.eligible_sfis_content_hash
                == manifest.eligible_sfis_content_hash
                and eligibility.upstream_content_hash == manifest.upstream_content_hash
            ),
        )


def _validate_source_credit(
    *, edge: GraphRelationship, evidence: _Evidence, provenance: Provenance
) -> None:
    """Check source identity/license and LP generator credit independently of hierarchy.

    Parameters
    ----------
    edge
        Decoded exported LP relationship.
    evidence
        Original framework and public document identity.
    provenance
        Retained source and generator evidence.

    Examples
    --------
    >>> _validate_source_credit(edge=edge, evidence=evidence, provenance=provenance)
    """

    root = evidence.package.framework_root
    source = provenance.source_framework
    expected_source = {
        "attribution_statement": root.attribution_statement,
        "author": root.author,
        "case_identifier_uuid": root.case_identifier_uuid,
        "license": root.license,
        "provider": root.provider,
        "title": root.name,
    }
    identity = (
        f"lc:curriculum:{provenance.doc_key}:relationship:{edge.label}:"
        f"{edge.source_entity_value}:{edge.target_entity_value}"
    )
    _require(
        code="lp_source_credit_mismatch",
        condition=(
            source.model_dump() == expected_source
            and provenance.relationship_identity_key == identity
            and provenance.approved_by == edge.provider == "IDinsight"
            and edge.author == "LLM generated"
            and edge.license == root.license
            and provenance.attribution_statement_template == _ATTRIBUTION_TEMPLATE
            and edge.attribution_statement
            == _ATTRIBUTION_TEMPLATE.format(
                source_attribution_statement=root.attribution_statement
            )
        ),
        record_id=str(edge.relationship_id),
    )


def validate_learning_progression_evidence(
    *, captured_contents: Mapping[str, bytes], package: LoadedGraphPackage
) -> tuple[LearningProgressionEvidence | None, tuple[PackageValidationFinding, ...]]:
    """Independently accept complete LP evidence and release all rich source maps.

    Parameters
    ----------
    captured_contents
        Exact bytes checksum-verified by the established loader.
    package
        Decoded immutable package before semantic acceptance.

    Returns
    -------
    tuple[LearningProgressionEvidence | None, tuple[PackageValidationFinding, ...]]
        Small validated projections and safe findings. Non-LP packages need no evidence.

    Examples
    --------
    >>> projection, findings = validate_learning_progression_evidence(
    ...     captured_contents=verified_bytes, package=valid_package
    ... )
    >>> findings
    ()
    """

    if GraphType.LEARNING_PROGRESSIONS not in package.manifest.included_graph_types:
        return None, ()

    try:
        evidence = _load_evidence(contents=captured_contents, package=package)
        _validate_index(evidence)
        _validate_normalization(evidence)
        accepted = _validate_final_claims(evidence)
        judgments = _validate_provenance(accepted=accepted, evidence=evidence)
        _validate_report(evidence)
        projection = LearningProgressionEvidence(
            coverage=_coverage(evidence), judgments=judgments
        )
    except _EvidenceError as error:
        return None, (
            PackageValidationFinding(
                code=error.code,
                message="LP evidence fails an independent package acceptance check.",
                record_id=error.record_id,
            ),
        )
    except (KeyError, ManifestBuildError, TypeError, ValidationError, ValueError):
        return None, (
            PackageValidationFinding(
                code="lp_evidence_shape",
                message="Required LP evidence is missing or malformed.",
            ),
        )

    return projection, ()
