"""Strict source and generated evidence contracts for local LP preparation."""

# Standard Library
from typing import Literal

# Third Party Library
from pydantic import ConfigDict, Field, StrictBool, StrictStr

# Package Library
from kgfegmcp.domain.identifiers import (
    ArtifactPath,
    CaseIdentifierUuid,
    FrameworkId,
    NodeId,
    RelationshipId,
    Sha256Digest,
)
from kgfegmcp.packages.models import NonNegativeStrictInt
from kgfegmcp.schemas import FrozenSchema


# Copied source and identity contracts.
class CopiedFile(FrozenSchema):
    """Select the verified, repository-relative part of a local copy receipt."""

    destination_path: ArtifactPath
    destination_sha256: Sha256Digest
    document_key: StrictStr
    framework_id: FrameworkId
    size_bytes: NonNegativeStrictInt
    source_sha256_after: Sha256Digest
    source_sha256_before: Sha256Digest
    verified: Literal[True]

    model_config = ConfigDict(extra="ignore")


class CopiedFramework(FrozenSchema):
    """Identify one copied framework without retaining private source paths."""

    destination_directory: ArtifactPath
    document_key: StrictStr = Field(pattern=r"^[0-9a-f]{64}$")
    framework_case_uuid: CaseIdentifierUuid
    framework_id: FrameworkId

    model_config = ConfigDict(extra="ignore")


class CopyReceipt(FrozenSchema):
    """Read only the local verification fields needed by preparation."""

    files: tuple[CopiedFile, ...]
    frameworks: tuple[CopiedFramework, ...]
    receipt_version: Literal["1.0"]
    selected_file_count: NonNegativeStrictInt
    status: Literal["verified"]

    model_config = ConfigDict(extra="ignore")


class DetailedLearningProgression(FrozenSchema):
    """Preserve one snake-case source edge and its unmodified rich metadata."""

    attribution_statement: StrictStr
    author: StrictStr
    date_created: StrictStr | None
    date_modified: StrictStr | None
    description: StrictStr
    identifier: RelationshipId
    license: StrictStr
    metadata: dict[str, object]
    provider: StrictStr
    relationship_type: Literal["buildsTowards", "relatesTo"]
    source_entity: Literal["StandardsFrameworkItem"]
    source_entity_key: Literal["case_identifier_uuid", "caseIdentifierUUID"]
    source_entity_value: CaseIdentifierUuid
    target_entity: Literal["StandardsFrameworkItem"]
    target_entity_key: Literal["case_identifier_uuid", "caseIdentifierUUID"]
    target_entity_value: CaseIdentifierUuid

    model_config = ConfigDict(alias_generator=None)


class StandardIdentity(FrozenSchema):
    """Resolve an unchanged standards CASE selector to its existing outer ID."""

    case_identifier_uuid: CaseIdentifierUuid
    node_id: NodeId


# Generated preparation evidence; the index follows its partition dependency.
class NormalizationReceipt(FrozenSchema):
    """Retain public preparation hashes and decisions without external paths."""

    as_lc_relationship_prefix_bytes: NonNegativeStrictInt
    builds_towards_relationships: NonNegativeStrictInt
    copy_receipt_sha256: Sha256Digest
    document_key: StrictStr
    format_version: Literal["1.0"] = "1.0"
    framework_case_uuid: CaseIdentifierUuid
    framework_id: FrameworkId
    input_sha256: dict[str, Sha256Digest]
    newline_separator_added: StrictBool
    output_sha256: dict[ArtifactPath, Sha256Digest]
    relates_to_relationships: NonNegativeStrictInt


class PreparationResult(FrozenSchema):
    """Return relative preparation identities without claiming package acceptance."""

    builds_towards_relationships: NonNegativeStrictInt
    framework_id: FrameworkId
    output_directory: StrictStr
    outcome: Literal["created", "existing_identical"]
    relates_to_relationships: NonNegativeStrictInt
    sha256: dict[str, Sha256Digest]


class ProvenancePartition(FrozenSchema):
    """Bind one canonical provenance partition to its exact generated bytes."""

    artifact_path: ArtifactPath
    entry_count: NonNegativeStrictInt
    sha256: Sha256Digest


class LearningProgressionProvenanceIndex(FrozenSchema):
    """Describe deterministic partitions of an unchanged original provenance map."""

    format_version: Literal["1.0"] = "1.0"
    original_provenance_logical_name: Literal["learningProgressionProvenance"] = (
        "learningProgressionProvenance"
    )
    original_provenance_sha256: Sha256Digest
    partition_algorithm: Literal["SHA256(UTF8(relationship_id))[0] modulo 64"] = (
        "SHA256(UTF8(relationship_id))[0] modulo 64"
    )
    partition_count: Literal[64] = 64
    partitions: dict[str, ProvenancePartition]
